### ISSUE TITLE
OD的环境变量怎么写呀？跑不起来

### ISSUE THREAD

**Issue by linyali888** [Wenmoux/monster#1]
更新任务状态成功
共1个OD账号
--------开始OD账号1--------

{
  code: 1,
  msg: '獲取成功',
  is_watch: 1,
  data: {
    title: '觀看廣告可獲得 0.1 夢想豆',
    ftitle: 'Earn 0.1 ODseed',
    advertisement_id: 1
  }
}
去观看广告 1  Earn 0.1 ODseed

{ code: -1, msg: '獲取失敗', data: [] }
今日已观看0次广告
可用梦想豆：undefined
冻结梦想豆：undefined
更新任务状态成功

执行结束...

**Comment by Wenmoux** [comment]
例如export odStr="3929"

变量名odStr
就是user_id 随便抓个包就有了 多账号用@分割

**Comment by linyali888** [comment]
搞定 谢谢
