### ISSUE TITLE
10S阅读只阅读一次就停止了，报错！

### ISSUE THREAD

**Issue by shiyanzhizhuo** [Wenmoux/monster#2]
10s阅读, 开始!
共1个账号
账号【1】第1次阅读中
{"url":"http:\/\/mp.weixin.qq.com\/s?__biz=MjM5MjI1NzEwMA==&mid=2651779680&idx=1&sn=f9679598c4aeb2a1a2ac7b50b74f6e2d&scene=0#wechat_redirect","jkey":"MDAwMDAwMDAwMH6eu66FirSTvaqdzMfQjKGQfa3XhrHKlJmmvpiboZuEkYiseplolJO6ua2astCas4NmbrKIjaSU"}

==============📣系统通知📣==============
10s阅读
10s阅读账号【1】：该账号需要验证请手动阅读一次并关掉页面(不要点返回)

**Comment by ngrok-add** [comment]
我也是这样

**Comment by Wenmoux** [comment]
改了
